import { StyleSheet, Dimensions } from "react-native"
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFBFC",
  },
  header: {
    padding: 20,
    paddingTop: 60,
    backgroundColor: "#4A90E2",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 16,
    color: "#E3F2FD",
  },
  salarySection: {
    padding: 20,
    backgroundColor: "#FFFFFF",
    margin: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 15,
    color: "#1A1D29",
  },
  input: {
    backgroundColor: "#F9FAFB",
    borderColor: "#E5E7EB",
    borderWidth: 2,
    borderRadius: 12,
    padding: 16,
    fontSize: 18,
    marginBottom: 15,
    color: "#1A1D29",
  },
  disabledInput: {
    backgroundColor: "#E5E7EB",
    color: "#6B7280",
  },
  button: {
    backgroundColor: "#4A90E2",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  lockedButton: {
    backgroundColor: "#10B981",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  summarySection: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    marginTop: 0,
    borderRadius: 15,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 5,
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1A1D29",
  },
  remainingSection: {
    alignItems: "center",
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  remainingValue: {
    fontSize: 24,
    fontWeight: "bold",
  },
  chartSection: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    marginTop: 0,
    borderRadius: 15,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 10,
    color: "#1A1D29",
    textAlign: "center",
  },
  budgetCycleContainer: {
    alignItems: "center",
    marginBottom: 15,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#F3F4F6",
    borderRadius: 20,
    alignSelf: "center",
  },
  budgetCycleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4A90E2",
  },
  // New styles for category summary cards
  categorySummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingHorizontal: 5,
  },
  summaryCard: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 10,
    marginHorizontal: 3,
  },
  colorIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginBottom: 5,
  },
  categoryName: {
    fontSize: 11,
    color: "#6B7280",
    marginBottom: 3,
    textAlign: "center",
  },
  categoryAmount: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1A1D29",
    textAlign: "center",
  },
  expenseCategories: {
    margin: 20,
    marginTop: 0,
    marginBottom: 100,
  },
  categoryMain:{
    marginBottom: 100,
  },
  categorySection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  categoryIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 10,
  },
  categoryTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: "#1A1D29",
  },
  categoryTotal: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1A1D29",
  },
  expenseItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  expenseName: {
    fontSize: 14,
    textTransform: 'capitalize',
    color: "#6B7280",
  },
  expenseAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1D29",
  },
  noExpensesText: {
    fontSize: 14,
    color: "#9CA3AF",
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 10,
  },
})